title: PuppyTigerStudio
description: PuppyTigerStudio 공식 홈페이지
theme: jekyll-theme-minimal
markdown: kramdown

# GitHub Pages 설정
baseurl: ""
url: ""
repository: PuppyTigerSTUDIO/puppytigerstudio.github.io

# 언어 설정
lang: ko
